# Generated by Django 5.2.4 on 2025-07-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='ordenGeneratedDate',
            new_name='orderGeneratedDate',
        ),
        migrations.AlterField(
            model_name='course',
            name='dependencyCourseId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
