# Generated by Django 5.2.4 on 2025-07-11 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_ordengenerateddate_booking_ordergenerateddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='priceToPay',
        ),
        migrations.AddField(
            model_name='classroom',
            name='province',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='api.province'),
            preserve_default=False,
        ),
    ]
