# Generated by Django 5.2.4 on 2025-07-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_rol_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeravailability',
            name='time_str',
            field=models.CharField(default=None, max_length=24),
            preserve_default=False,
        ),
    ]
