# Generated by Django 5.2.4 on 2025-07-12 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_offeravailability_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='province',
        ),
    ]
