# Generated by Django 5.2.4 on 2025-07-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_classroom_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeravailability',
            name='time',
        ),
    ]
