# Generated by Django 5.2.4 on 2025-07-13 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_offeravailability_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offeravailability',
            old_name='time_str',
            new_name='time',
        ),
    ]
