# Generated by Django 5.2.4 on 2025-07-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_offeravailability_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='priceToPay',
        ),
        migrations.AlterField(
            model_name='booking',
            name='registeredDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
