# Generated by Django 5.2.4 on 2025-07-13 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_booking_classroom_remove_booking_pricetopay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='scheduleOfferDate',
        ),
        migrations.AddField(
            model_name='booking',
            name='offerAvailability',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.offeravailability'),
            preserve_default=False,
        ),
    ]
