# Generated by Django 5.2.4 on 2025-07-13 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_booking_scheduleofferdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='isHistory',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='orderGeneratedDate',
        ),
    ]
