# Generated by Django 5.2.4 on 2025-07-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_booking_ishistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='municipality',
        ),
    ]
