# Generated by Django 5.2.4 on 2025-07-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_classroom_municipality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actiontraces',
            options={'ordering': ['-created_at'], 'verbose_name': 'Traza', 'verbose_name_plural': 'Trazas'},
        ),
        migrations.RemoveField(
            model_name='actiontraces',
            name='registered_at',
        ),
        migrations.AddField(
            model_name='actiontraces',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
