# Generated by Django 5.2.4 on 2025-07-18 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_actiontraces_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='paymentCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='api.paymentcode'),
        ),
        migrations.AlterField(
            model_name='school',
            name='paymentCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='api.paymentcode'),
        ),
    ]
