# Generated by Django 5.2.4 on 2025-07-18 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_paymentcode_alter_course_paymentcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontraces',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
