# Generated by Django 5.2.4 on 2025-07-27 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_actiontraces_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentcode',
            options={'ordering': ['-id'], 'verbose_name': 'Código de Pago', 'verbose_name_plural': 'Códigos de Pagos'},
        ),
    ]
