# Generated by Django 5.2.4 on 2025-07-27 23:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_paymentcode_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransfermovilNotificationResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.IntegerField()),
                ('bank_id', models.CharField(max_length=255)),
                ('tm_id', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('msg', models.TextField()),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('bank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_pending', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notificación de Transfermóvil',
                'verbose_name_plural': 'Notificaciones de Transfermóvil',
            },
        ),
    ]
