# Generated by Django 5.2.5 on 2025-08-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_booking_created_at_classroom_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransfermovilNotificationResponse',
            new_name='TransfermovilNotification',
        ),
    ]
