# Generated by Django 5.2.5 on 2025-09-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_transfermovilnotificationresponse_transfermovilnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='isBookingReserve',
        ),
        migrations.RemoveField(
            model_name='course',
            name='bookingCode',
        ),
        migrations.RemoveField(
            model_name='course',
            name='dependencyCourseId',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor del sistema'), ('comercial', 'Equipo comercial'), ('observador', 'Usuario observador'), ('cajero', 'Cajero/Recepcionista')], default='observador', max_length=20),
        ),
    ]
