# Generated by Django 5.2.5 on 2025-09-24 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_booking_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.offer'),
        ),
    ]
