# Generated by Django 5.2.5 on 2025-09-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_booking_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='expirationDate',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='registeredDate',
        ),
    ]
