# Generated by Django 5.2.5 on 2025-09-30 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_booking_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='offerAvailability',
        ),
    ]
