from .UserViewset import UserViewset
from .ServiceViewset import ServiceViewset
from .ProvinceViewset import ProvinceViewset
from .MunicipalityViewset import MunicipalityViewset
from .SchoolViewset import SchoolViewset
from .ClientViewset import ClientViewset
from .CompanyViewset import CompanyViewset
from .DutiesrigthsViewset import DutiesrigthsViewset
from .ClassroomViewset import ClassroomViewset
from .CourseViewset import CourseViewset
from .OfferViewset import OfferViewset
from .MultipleBookingsViewset import MultipleBookingsViewset
from .BookingViewset import BookingViewset
from .OfferViewset import OfferListView
