from .CompanyPermission import CompanyPermission
from .ServicePermission import ServicePermission
from .CoursePermission import CoursePermission
from .OfferPermission import OfferPermission
from .MultipleBookingPermission import MultipleBookingPermission
from .ClassroomPermission import ClassroomPermission
from .IsAdminPermission import IsAdminPermission
